# Generated by Django 5.2.8 on 2025-11-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paygate', 'Carte Bancaire'), ('tmoney', 'T-Money'), ('flooz', 'Flooz')], default='paygate', max_length=20),
        ),
    ]
