# Generated by Django 5.2.8 on 2025-11-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='auth_code',
            new_name='identifier',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paygate_id',
            new_name='payment_reference',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='reference',
            new_name='tx_reference',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='risk_indicator',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='network',
            field=models.CharField(blank=True, choices=[('FLOOZ', 'FLOOZ'), ('TMONEY', 'T-Money')], max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='XOF', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('mobile_money', 'Mobile Money'), ('paygate', 'PayGate')], default='mobile_money', max_length=20),
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
